# CMake generated Testfile for 
# Source directory: /home/yun/Documents/refactor_backtrader/backtrader_cpp/tests
# Build directory: /home/yun/Documents/refactor_backtrader/backtrader_cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_analyzer-sqn "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_analyzer-sqn")
set_tests_properties(test_analyzer-sqn PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_analyzer-timereturn "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_analyzer-timereturn")
set_tests_properties(test_analyzer-timereturn PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_comminfo "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_comminfo")
set_tests_properties(test_comminfo PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_data_multiframe "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_data_multiframe")
set_tests_properties(test_data_multiframe PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_data_replay "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_data_replay")
set_tests_properties(test_data_replay PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_data_resample "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_data_resample")
set_tests_properties(test_data_resample PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_fractal "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_fractal")
set_tests_properties(test_fractal PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_accdecosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_accdecosc")
set_tests_properties(test_ind_accdecosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_aroonoscillator "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_aroonoscillator")
set_tests_properties(test_ind_aroonoscillator PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_aroonupdown "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_aroonupdown")
set_tests_properties(test_ind_aroonupdown PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_atr "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_atr")
set_tests_properties(test_ind_atr PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_awesomeoscillator "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_awesomeoscillator")
set_tests_properties(test_ind_awesomeoscillator PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_bbands "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_bbands")
set_tests_properties(test_ind_bbands PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_cci "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_cci")
set_tests_properties(test_ind_cci PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_dema "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_dema")
set_tests_properties(test_ind_dema PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_demaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_demaenvelope")
set_tests_properties(test_ind_demaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_demaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_demaosc")
set_tests_properties(test_ind_demaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_dm "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_dm")
set_tests_properties(test_ind_dm PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_dm_tolerance "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_dm_tolerance")
set_tests_properties(test_ind_dm_tolerance PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_dma "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_dma")
set_tests_properties(test_ind_dma PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_downmove "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_downmove")
set_tests_properties(test_ind_downmove PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_dpo "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_dpo")
set_tests_properties(test_ind_dpo PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_dv2 "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_dv2")
set_tests_properties(test_ind_dv2 PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_ema "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_ema")
set_tests_properties(test_ind_ema PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_emaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_emaenvelope")
set_tests_properties(test_ind_emaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_emaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_emaosc")
set_tests_properties(test_ind_emaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_envelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_envelope")
set_tests_properties(test_ind_envelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_heikinashi "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_heikinashi")
set_tests_properties(test_ind_heikinashi PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_highest "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_highest")
set_tests_properties(test_ind_highest PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_hma "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_hma")
set_tests_properties(test_ind_hma PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_ichimoku "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_ichimoku")
set_tests_properties(test_ind_ichimoku PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_kama "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_kama")
set_tests_properties(test_ind_kama PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_kamaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_kamaenvelope")
set_tests_properties(test_ind_kamaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_kamaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_kamaosc")
set_tests_properties(test_ind_kamaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_kst "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_kst")
set_tests_properties(test_ind_kst PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_lowest "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_lowest")
set_tests_properties(test_ind_lowest PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_lrsi "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_lrsi")
set_tests_properties(test_ind_lrsi PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_macdhisto "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_macdhisto")
set_tests_properties(test_ind_macdhisto PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_minperiod "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_minperiod")
set_tests_properties(test_ind_minperiod PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_minperiod_simple "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_minperiod_simple")
set_tests_properties(test_ind_minperiod_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_momentum "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_momentum")
set_tests_properties(test_ind_momentum PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_momentumoscillator "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_momentumoscillator")
set_tests_properties(test_ind_momentumoscillator PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_oscillator "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_oscillator")
set_tests_properties(test_ind_oscillator PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_pctchange "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_pctchange")
set_tests_properties(test_ind_pctchange PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_pctrank "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_pctrank")
set_tests_properties(test_ind_pctrank PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_pgo "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_pgo")
set_tests_properties(test_ind_pgo PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_ppo "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_ppo")
set_tests_properties(test_ind_ppo PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_pposhort "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_pposhort")
set_tests_properties(test_ind_pposhort PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_priceosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_priceosc")
set_tests_properties(test_ind_priceosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_rmi "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_rmi")
set_tests_properties(test_ind_rmi PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_roc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_roc")
set_tests_properties(test_ind_roc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_rsi "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_rsi")
set_tests_properties(test_ind_rsi PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_sma "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_sma")
set_tests_properties(test_ind_sma PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_smaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_smaenvelope")
set_tests_properties(test_ind_smaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_smaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_smaosc")
set_tests_properties(test_ind_smaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_smma "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_smma")
set_tests_properties(test_ind_smma PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_smmaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_smmaenvelope")
set_tests_properties(test_ind_smmaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_smmaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_smmaosc")
set_tests_properties(test_ind_smmaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_stochastic "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_stochastic")
set_tests_properties(test_ind_stochastic PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_stochasticfull "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_stochasticfull")
set_tests_properties(test_ind_stochasticfull PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_sumn "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_sumn")
set_tests_properties(test_ind_sumn PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_tema "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_tema")
set_tests_properties(test_ind_tema PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_temaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_temaenvelope")
set_tests_properties(test_ind_temaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_temaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_temaosc")
set_tests_properties(test_ind_temaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_trix "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_trix")
set_tests_properties(test_ind_trix PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_tsi "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_tsi")
set_tests_properties(test_ind_tsi PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_ultosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_ultosc")
set_tests_properties(test_ind_ultosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_upmove "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_upmove")
set_tests_properties(test_ind_upmove PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_vortex "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_vortex")
set_tests_properties(test_ind_vortex PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_williamsad "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_williamsad")
set_tests_properties(test_ind_williamsad PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_williamsr "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_williamsr")
set_tests_properties(test_ind_williamsr PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_wma "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_wma")
set_tests_properties(test_ind_wma PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_wmaenvelope "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_wmaenvelope")
set_tests_properties(test_ind_wmaenvelope PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_wmaosc "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_wmaosc")
set_tests_properties(test_ind_wmaosc PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_zlema "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_zlema")
set_tests_properties(test_ind_zlema PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_ind_zlind "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_ind_zlind")
set_tests_properties(test_ind_zlind PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_macd_framework "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_macd_framework")
set_tests_properties(test_macd_framework PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_metaclass "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_metaclass")
set_tests_properties(test_metaclass PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_order "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_order")
set_tests_properties(test_order PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_position "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_position")
set_tests_properties(test_position PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_strategy_optimized "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_strategy_optimized")
set_tests_properties(test_strategy_optimized PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_strategy_unoptimized "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_strategy_unoptimized")
set_tests_properties(test_strategy_unoptimized PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_trade "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_trade")
set_tests_properties(test_trade PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
add_test(test_writer "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/test_writer")
set_tests_properties(test_writer PROPERTIES  _BACKTRACE_TRIPLES "/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;47;add_test;/home/yun/Documents/refactor_backtrader/backtrader_cpp/tests/CMakeLists.txt;0;")
